version: '3.9'

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: shopflow-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: shopflow-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_logs:/opt/sonarqube/logs
    restart: unless-stopped
/*sqa_b5effb7b342172dd0f67741333396cac379e12ae*/
volumes:
  jenkins_home:
  sonar_data:
  sonar_logs:
